// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDirsb1ourdI5Zp0rnOuBra0vcQn7Ktkek',
    appId: '1:856969113111:web:fd468ea86bd28d07637652',
    messagingSenderId: '856969113111',
    projectId: 'project-d281b',
    authDomain: 'project-d281b.firebaseapp.com',
    storageBucket: 'project-d281b.appspot.com',
    measurementId: 'G-HFH4FK50MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrhJFFk8Do_jSihm1HlyXS-Glj8eyRRE',
    appId: '1:856969113111:android:c0623f60970c057e637652',
    messagingSenderId: '856969113111',
    projectId: 'project-d281b',
    storageBucket: 'project-d281b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUC7WrRUCSRVyZw9o39xElWw9Y4KLXSqM',
    appId: '1:856969113111:ios:143a7993816c9d59637652',
    messagingSenderId: '856969113111',
    projectId: 'project-d281b',
    storageBucket: 'project-d281b.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUC7WrRUCSRVyZw9o39xElWw9Y4KLXSqM',
    appId: '1:856969113111:ios:143a7993816c9d59637652',
    messagingSenderId: '856969113111',
    projectId: 'project-d281b',
    storageBucket: 'project-d281b.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDirsb1ourdI5Zp0rnOuBra0vcQn7Ktkek',
    appId: '1:856969113111:web:790dabe031504f07637652',
    messagingSenderId: '856969113111',
    projectId: 'project-d281b',
    authDomain: 'project-d281b.firebaseapp.com',
    storageBucket: 'project-d281b.appspot.com',
    measurementId: 'G-8HBYB3CQ2W',
  );
}
